"""Deterministic checks for M14 AI-authored PR provenance fixtures and workflow."""

from __future__ import annotations

import re
from typing import Any


EXPECTED_TOP_LEVEL_FIELDS = {
    "fixture_status": "m14_active_work_not_complete",
    "related_issue": "#180",
    "tracker_issue": "#201",
    "tracker_issue_linkage": "Refs #201",
    "related_voice_runtime_pr": "#202",
    "related_public_output_gate_pr": "#204",
    "related_moda_mapping_pr": "#205",
    "m14_completion_status": "active_work_not_complete",
    "target_future_release": "v0.13.0",
    "workflow_event": "pull_request_target",
}

BOOLEAN_EXPECTATIONS = {
    "workflow_executes_pr_code": False,
    "pull_request_head_checked_out": False,
    "third_party_runtime_action_used": False,
    "merge_gate_created": False,
    "decision_proof_sealed_by_fixture": False,
    "final_authorship_judgment_made_by_fixture": False,
}

EXPECTED_PERMISSIONS = {
    "contents": "read",
    "issues": "write",
    "pull-requests": "write",
}

REQUIRED_EVENT_TYPES = {
    "opened",
    "edited",
    "synchronize",
    "reopened",
    "labeled",
    "unlabeled",
    "ready_for_review",
}

REQUIRED_WORKFLOW_OUTPUTS = {
    "is-agent-pr",
    "agent",
    "detection-signals",
    "sensitive-change",
    "review-routing-required",
    "reviewer-request-status",
}

REQUIRED_AGENTS = {
    "codex",
    "claude_code",
    "github_copilot",
    "cursor",
    "devin",
    "google_jules",
    "aider",
    "openhands",
    "sweep",
}

REQUIRED_BRANCH_PREFIXES = {
    "codex/",
    "claude/",
    "copilot/",
    "cursor/",
    "devin/",
    "jules/",
    "aider/",
    "openhands/",
    "sweep/",
}

REQUIRED_MARKERS = {
    "AI-Authored: true",
    "Agent-Authored: true",
    "Generated by Codex",
    "Generated with Claude Code",
    "Co-authored-by references associated with an agent",
}

REQUIRED_SENSITIVE_PATHS = {
    ".github/workflows/",
    "runtime/",
    "tests/",
    "docs/public-integration-pack/",
    "examples/public-integration-pack-pilot/",
    "README.md",
    "SECURITY.md",
    "CODEOWNERS",
    "release-related paths or files",
}

REQUIRED_CASE_TYPES = {
    "codex_pr_detected_from_structured_pr_body_marker",
    "claude_code_detected_from_commit_or_coauthored_by_marker",
    "cursor_detected_from_branch_prefix",
    "copilot_detected_from_author_or_branch_signal",
    "manually_labeled_pr_by_ai",
    "ai_authored_pr_changing_governance_sensitive_files",
    "ai_authored_pr_changing_only_non_sensitive_documentation",
    "ordinary_human_pr_with_no_ai_signal",
    "repeated_workflow_run_updates_sticky_comment_without_duplication",
    "missing_reviewer_configuration_remains_non_blocking",
    "reviewer_api_failure_remains_non_blocking",
    "attempt_to_treat_pr_by_ai_as_approval",
    "attempt_to_treat_human_review_required_as_completed_review",
    "attempt_to_treat_reviewer_routing_as_approval",
    "attempt_to_treat_workflow_success_as_merge_approval",
    "attempt_to_treat_detection_as_final_identity_judgment",
    "attempt_to_seal_decision_proof",
    "attempt_to_close_tracker_issue_201",
    "attempt_to_declare_m14_complete",
    "attempt_to_declare_v0_13_0_released",
}

REQUIRED_BOUNDARY_STATEMENTS = {
    "AI-authored detection is provenance evidence, not identity proof.",
    "pr-by-ai is not approval.",
    "human-review-required is not completed review.",
    "Reviewer routing is not review approval.",
    "Workflow success is not merge approval.",
    "This workflow is not a security scanner.",
    "This workflow is not a policy authority.",
    "This workflow is not a Decision Proof verification or sealing engine.",
    "Decision Proof sealing remains AAOS-owned.",
    "AAOS remains the decision sovereignty layer.",
}

REQUIRED_ALLOWED_OUTPUTS = {
    "ai_pr_provenance_valid",
    "ai_pr_provenance_invalid",
    "agent_pr_detected",
    "non_agent_pr_detected",
    "provenance_label_required",
    "provenance_comment_required",
    "sensitive_change_detected",
    "human_review_required",
    "reviewer_routing_required",
    "reviewer_routing_not_configured",
    "reviewer_request_succeeded",
    "reviewer_request_warning",
    "ready_for_review",
    "escalation_required",
}

FORBIDDEN_EVALUATOR_OUTPUTS = {
    "ai_authorship_certified",
    "human_authorship_certified",
    "identity_proven",
    "provenance_approved",
    "merge_approved",
    "review_approved",
    "reviewer_routing_is_approval",
    "security_scan_passed",
    "policy_approved",
    "risk_accepted",
    "audit_closed",
    "waiver_granted",
    "fail_closed_executed",
    "rollback_executed",
    "decision_proof_verified",
    "decision_proof_sealed",
    "sealed_by_provenance_workflow",
    "sealed_by_evaluator",
    "authority_transferred",
    "final_governance_judgment",
    "m14_complete",
    "v0_13_0_released",
    "closes_201",
}

STICKY_MARKER = "<!-- aaos:m14-ai-pr-provenance -->"

AGENT_TOKENS = {
    "codex": ("codex",),
    "claude_code": ("claude-code", "claude_code", "claude code", "claude"),
    "github_copilot": (
        "github-copilot",
        "github_copilot",
        "github copilot",
        "copilot",
    ),
    "cursor": ("cursor",),
    "devin": ("devin",),
    "google_jules": ("google-jules", "google_jules", "google jules", "jules"),
    "aider": ("aider",),
    "openhands": ("openhands", "open-hands", "open hands"),
    "sweep": ("sweep",),
}

BRANCH_PREFIXES = {
    "codex": "codex/",
    "claude_code": "claude/",
    "github_copilot": "copilot/",
    "cursor": "cursor/",
    "devin": "devin/",
    "google_jules": "jules/",
    "aider": "aider/",
    "openhands": "openhands/",
    "sweep": "sweep/",
}

GENERATION_MARKERS = {
    "codex": ("generated by codex", "generated with codex"),
    "claude_code": ("generated by claude code", "generated with claude code"),
    "github_copilot": (
        "generated by github copilot",
        "generated with github copilot",
    ),
    "cursor": ("generated by cursor", "generated with cursor"),
    "devin": ("generated by devin", "generated with devin"),
    "google_jules": ("generated by google jules", "generated with google jules"),
    "aider": ("generated by aider", "generated with aider"),
    "openhands": ("generated by openhands", "generated with openhands"),
    "sweep": ("generated by sweep", "generated with sweep"),
}


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _string_set(value: Any) -> set[str]:
    return {str(item).strip() for item in _as_list(value) if str(item).strip()}


def _norm(value: Any) -> str:
    return str(value or "").strip().casefold()


def _dedupe(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _sensitive_path(path: Any) -> bool:
    normalized = str(path or "").replace("\\", "/").lstrip("./")
    lowered = normalized.casefold()
    basename = lowered.rsplit("/", 1)[-1]
    if lowered.startswith(
        (
            ".github/workflows/",
            "runtime/",
            "tests/",
            "docs/public-integration-pack/",
            "examples/public-integration-pack-pilot/",
            "release/",
            "releases/",
        )
    ):
        return True
    if basename in {"readme.md", "security.md", "codeowners"}:
        return True
    return (
        basename.startswith("changelog")
        or basename.startswith("release-")
        or basename.endswith(".release.json")
        or "/release/" in lowered
        or "/releases/" in lowered
    )


def detect_agent_pr(case: dict[str, Any]) -> tuple[bool, str, list[str]]:
    """Return deterministic heuristic detection for one fixture case."""

    signals: list[str] = []
    candidates: list[str] = []
    author = _norm(case.get("pr_author_login"))
    branch = _norm(case.get("head_branch"))
    pr_text = f"{case.get('pr_title', '')}\n{case.get('pr_body', '')}".casefold()
    labels = {_norm(label) for label in _as_list(case.get("existing_labels"))}

    for agent, tokens in AGENT_TOKENS.items():
        if any(token in author for token in tokens):
            signals.append(f"author:{agent}")
            candidates.append(agent)

    for agent, prefix in BRANCH_PREFIXES.items():
        if branch.startswith(prefix):
            signals.append(f"branch_prefix:{prefix}")
            candidates.append(agent)

    if re.search(
        r"(?im)^\s*(ai-authored|agent-authored)\s*:\s*true\s*$", pr_text
    ):
        signals.append("structured_marker:agent_authored_true")

    for agent, markers in GENERATION_MARKERS.items():
        if any(marker in pr_text for marker in markers):
            signals.append(f"pr_marker:{agent}")
            candidates.append(agent)

    for raw_message in _as_list(case.get("commit_messages")):
        message = _norm(raw_message)
        if re.search(
            r"(?im)^\s*(ai-authored|agent-authored)\s*:\s*true\s*$", message
        ):
            signals.append("commit_marker:agent_authored_true")
        for agent, markers in GENERATION_MARKERS.items():
            if any(marker in message for marker in markers):
                signals.append(f"commit_marker:{agent}")
                candidates.append(agent)
        coauthor_lines = re.findall(r"(?im)^\s*co-authored-by\s*:\s*(.+)$", message)
        for agent, tokens in AGENT_TOKENS.items():
            if any(any(token in line for token in tokens) for line in coauthor_lines):
                signals.append(f"coauthor:{agent}")
                candidates.append(agent)

    if "pr-by-ai" in labels:
        signals.append("label:pr-by-ai")

    signals = _dedupe(signals)
    return bool(signals), candidates[0] if candidates else "unknown", signals


def _computed_case_state(case: dict[str, Any]) -> dict[str, Any]:
    detected, agent, signals = detect_agent_pr(case)
    sensitive_files = sorted(
        str(path)
        for path in _as_list(case.get("changed_files"))
        if _sensitive_path(path)
    )
    sensitive = bool(sensitive_files)
    review_routing_required = detected and sensitive
    reviewer_status = "not_required"

    if review_routing_required:
        config = _as_dict(case.get("reviewer_configuration"))
        author = _norm(case.get("pr_author_login"))
        reviewers = {
            str(item).strip().lstrip("@")
            for item in _as_list(config.get("reviewers"))
            if str(item).strip().lstrip("@")
            and _norm(str(item).strip().lstrip("@")) != author
        }
        teams = {
            str(item).strip().lstrip("@")
            for item in _as_list(config.get("teams"))
            if str(item).strip().lstrip("@")
        }
        if not reviewers and not teams:
            reviewer_status = "reviewer_routing_not_configured"
        elif _norm(case.get("reviewer_api_result")) == "failure":
            reviewer_status = "reviewer_request_warning"
        else:
            reviewer_status = "reviewer_request_succeeded"

    prior_comments = case.get("prior_sticky_comment_count", 0)
    prior_comments = prior_comments if isinstance(prior_comments, int) else 0
    comment_action = "none"
    resulting_comments = prior_comments
    if detected:
        comment_action = "update" if prior_comments else "create"
        resulting_comments = 1

    return {
        "detected": detected,
        "agent": agent if detected else "unknown",
        "detection_signals": signals,
        "sensitive_change": sensitive,
        "sensitive_files": sensitive_files,
        "add_pr_by_ai": detected,
        "add_human_review_required": review_routing_required,
        "comment_action": comment_action,
        "resulting_sticky_comment_count": resulting_comments,
        "review_routing_required": review_routing_required,
        "reviewer_request_status": reviewer_status,
        "pr_modified": detected,
        "author_requested_as_reviewer": False,
        "unrelated_labels_preserved": True,
        "non_blocking": True,
    }


def _extract_mapping_block(text: str, name: str) -> dict[str, str]:
    match = re.search(
        rf"(?ms)^{re.escape(name)}:\s*\n(?P<body>(?:  [^\n]*\n)+)", text
    )
    if not match:
        return {}
    result: dict[str, str] = {}
    for key, value in re.findall(r"(?m)^  ([A-Za-z0-9_-]+):\s*([^#\n]+?)\s*$", match.group("body")):
        result[key] = value.strip().strip('"\'')
    return result


def evaluate_workflow_text(workflow_text: Any) -> list[str]:
    """Validate workflow security invariants without loading YAML."""

    findings: list[str] = []
    if not isinstance(workflow_text, str) or not workflow_text.strip():
        return ["workflow_text_missing"]

    event_match = re.search(
        r"(?ms)^  pull_request_target:\s*\n(?P<body>.*?)(?=^[A-Za-z_][A-Za-z0-9_-]*:|\Z)",
        workflow_text,
    )
    if not event_match:
        findings.append("pull_request_target_event_missing")
    else:
        event_types = set(
            re.findall(r"(?m)^\s{6}-\s+([A-Za-z0-9_-]+)\s*$", event_match.group("body"))
        )
        if event_types != REQUIRED_EVENT_TYPES:
            findings.append("pull_request_target_event_types_invalid")

    if re.search(r"(?m)^\s{2}pull_request:\s*$", workflow_text):
        findings.append("untrusted_pull_request_event_present")

    permissions = _extract_mapping_block(workflow_text, "permissions")
    if permissions != EXPECTED_PERMISSIONS:
        findings.append("workflow_permissions_invalid")

    if "runs-on: ubuntu-latest" not in workflow_text:
        findings.append("ubuntu_latest_runner_missing")
    if re.search(r"(?m)^\s*uses\s*:", workflow_text):
        findings.append("uses_step_present")
    if "actions/checkout" in workflow_text.casefold():
        findings.append("actions_checkout_present")

    forbidden_execution_patterns = {
        "git_checkout": r"\bgit\s+checkout\b",
        "git_switch": r"\bgit\s+switch\b",
        "git_clone": r"\bgit\s+clone\b",
        "subprocess": r"\bsubprocess\b",
        "os_system": r"\bos\.system\s*\(",
        "python_eval": r"\beval\s*\(",
        "python_exec": r"\bexec\s*\(",
        "archive_download": r"/(zipball|tarball)\b",
        "content_download": r"\b(download_url|contents_url)\b",
    }
    for name, pattern in forbidden_execution_patterns.items():
        if re.search(pattern, workflow_text, flags=re.IGNORECASE):
            findings.append(f"pull_request_code_execution_surface_present:{name}")

    required_security_tokens = {
        "inline_python_missing": "python - <<'PY'",
        "event_path_missing": "GITHUB_EVENT_PATH",
        "github_token_missing": "GITHUB_TOKEN",
        "rest_transport_missing": "urllib.request",
        "warning_annotation_missing": "::warning::",
        "non_blocking_exit_missing": "sys.exit(0)",
        "reviewer_variable_missing": "AAOS_AI_PR_REVIEWERS",
        "review_team_variable_missing": "AAOS_AI_PR_REVIEW_TEAMS",
        "review_request_endpoint_missing": "requested_reviewers",
        "comment_update_endpoint_missing": "issues/comments/",
    }
    for finding, token in required_security_tokens.items():
        if token not in workflow_text:
            findings.append(finding)

    if re.search(r"print\s*\([^\n]*(GITHUB_TOKEN|\btoken\b)", workflow_text, re.IGNORECASE):
        findings.append("github_token_logging_surface_present")
    if re.search(r"(?m)^\s*(pip|python\s+-m\s+pip)\s+install\b", workflow_text):
        findings.append("non_standard_library_install_present")

    if workflow_text.count(STICKY_MARKER) != 1:
        findings.append("sticky_comment_marker_not_unique_in_workflow")
    if '"PATCH"' not in workflow_text or '"POST"' not in workflow_text:
        findings.append("sticky_comment_upsert_behavior_incomplete")

    for output_name in REQUIRED_WORKFLOW_OUTPUTS:
        output_pattern = rf"(?m)^\s{{6}}{re.escape(output_name)}:\s*\$\{{\{{"
        if not re.search(output_pattern, workflow_text):
            findings.append(f"workflow_output_missing:{output_name}")

    for statement in REQUIRED_BOUNDARY_STATEMENTS:
        if statement not in workflow_text:
            findings.append(f"workflow_boundary_statement_missing:{statement}")

    if "pull_request_target is used only because this workflow executes the trusted" not in workflow_text:
        findings.append("pull_request_target_security_comment_missing")
    if "never checks out or executes pull-request code" not in workflow_text:
        findings.append("pull_request_target_no_execution_comment_missing")

    return _dedupe(findings)


def _validate_fixture_contract(fixture_set: dict[str, Any]) -> list[str]:
    findings: list[str] = []
    for field, expected in EXPECTED_TOP_LEVEL_FIELDS.items():
        if fixture_set.get(field) != expected:
            findings.append(f"top_level_field_invalid:{field}")
    for field, expected in BOOLEAN_EXPECTATIONS.items():
        if fixture_set.get(field) is not expected:
            findings.append(f"top_level_boolean_invalid:{field}")

    release_path = _as_dict(fixture_set.get("future_release_tag_path"))
    if release_path.get("released") is not False:
        findings.append("future_release_tag_path_released_must_be_false")

    security = _as_dict(fixture_set.get("workflow_security_model"))
    if _as_dict(security.get("permissions")) != EXPECTED_PERMISSIONS:
        findings.append("fixture_permissions_invalid")
    security_expectations = {
        "trusted_workflow_definition": "base_branch",
        "runner": "ubuntu-latest",
        "implementation": "inline_python_standard_library_only",
        "event_source": "GITHUB_EVENT_PATH",
        "pull_request_controlled_strings": "untrusted_data",
        "token_logged": False,
        "mutation_failures_blocking": False,
        "pull_request_workflow_definition_used": False,
        "pull_request_files_downloaded": False,
        "shell_commands_derived_from_pr_content": False,
    }
    for field, expected in security_expectations.items():
        if security.get(field) != expected:
            findings.append(f"workflow_security_model_invalid:{field}")

    if fixture_set.get("sticky_comment_marker") != STICKY_MARKER:
        findings.append("sticky_comment_marker_invalid")
    if _string_set(fixture_set.get("recognized_agents")) != REQUIRED_AGENTS:
        findings.append("recognized_agents_incomplete")
    if _string_set(fixture_set.get("recognized_branch_prefixes")) != REQUIRED_BRANCH_PREFIXES:
        findings.append("recognized_branch_prefixes_incomplete")
    if not REQUIRED_MARKERS.issubset(_string_set(fixture_set.get("recognized_markers"))):
        findings.append("recognized_markers_incomplete")
    if not REQUIRED_SENSITIVE_PATHS.issubset(
        _string_set(fixture_set.get("governance_sensitive_paths"))
    ):
        findings.append("governance_sensitive_paths_incomplete")
    if _string_set(fixture_set.get("workflow_outputs")) != REQUIRED_WORKFLOW_OUTPUTS:
        findings.append("workflow_outputs_incomplete")

    boundaries = _string_set(fixture_set.get("required_boundary_statements"))
    if not REQUIRED_BOUNDARY_STATEMENTS.issubset(boundaries):
        findings.append("governance_boundary_statements_incomplete")

    allowed = _string_set(fixture_set.get("allowed_evaluator_outputs"))
    forbidden = _string_set(fixture_set.get("forbidden_evaluator_outputs"))
    if not REQUIRED_ALLOWED_OUTPUTS.issubset(allowed):
        findings.append("allowed_evaluator_outputs_incomplete")
    if not FORBIDDEN_EVALUATOR_OUTPUTS.issubset(forbidden):
        findings.append("forbidden_evaluator_outputs_incomplete")
    if allowed & forbidden:
        findings.append("allowed_and_forbidden_outputs_overlap")

    labels = _as_dict(fixture_set.get("provenance_labels"))
    pr_by_ai = _as_dict(labels.get("pr-by-ai"))
    human_review = _as_dict(labels.get("human-review-required"))
    if pr_by_ai.get("color") != "8250df" or pr_by_ai.get("meaning") != "provenance_metadata_only":
        findings.append("pr_by_ai_label_contract_invalid")
    if (
        human_review.get("color") != "d93f0b"
        or human_review.get("meaning") != "review_routing_metadata_only"
    ):
        findings.append("human_review_label_contract_invalid")

    reviewer = _as_dict(fixture_set.get("reviewer_configuration"))
    reviewer_expectations = {
        "reviewer_variable": "AAOS_AI_PR_REVIEWERS",
        "team_variable": "AAOS_AI_PR_REVIEW_TEAMS",
        "format": "comma_separated",
        "author_excluded": True,
        "routing_is_advisory": True,
        "missing_configuration_status": "reviewer_routing_not_configured",
        "api_failure_status": "reviewer_request_warning",
    }
    for field, expected in reviewer_expectations.items():
        if reviewer.get(field) != expected:
            findings.append(f"reviewer_configuration_invalid:{field}")

    return findings


def _evaluate_case(case: dict[str, Any]) -> dict[str, Any]:
    case_id = str(case.get("case_id") or "missing-case-id")
    case_type = str(case.get("case_type") or "missing-case-type")
    attempted_output = str(case.get("attempted_evaluator_output") or "").strip()
    if attempted_output:
        rejected = attempted_output in FORBIDDEN_EVALUATOR_OUTPUTS
        expected_rejection = case.get("expected_result") == "rejected"
        findings = []
        if not rejected:
            findings.append("forbidden_attempt_not_rejected")
        if not expected_rejection:
            findings.append("negative_case_expected_result_invalid")
        return {
            "case_id": case_id,
            "case_type": case_type,
            "case_valid": rejected and expected_rejection,
            "attempted_output": attempted_output,
            "attempt_rejected": rejected,
            "findings": findings,
        }

    computed = _computed_case_state(case)
    expected = _as_dict(case.get("expected"))
    findings: list[str] = []
    compared_fields = {
        "detected",
        "agent",
        "add_pr_by_ai",
        "add_human_review_required",
        "comment_action",
        "review_routing_required",
        "reviewer_request_status",
        "non_blocking",
    }
    for field in compared_fields:
        if field not in expected:
            findings.append(f"expected_field_missing:{field}")
        elif expected[field] != computed[field]:
            findings.append(f"expected_field_mismatch:{field}")

    for optional_field in {
        "resulting_sticky_comment_count",
        "pr_modified",
        "author_requested_as_reviewer",
        "unrelated_labels_preserved",
    }:
        if optional_field in expected and expected[optional_field] != computed[optional_field]:
            findings.append(f"expected_field_mismatch:{optional_field}")

    if computed["add_pr_by_ai"] and not computed["detected"]:
        findings.append("pr_by_ai_added_without_agent_detection")
    if not computed["detected"] and computed["pr_modified"]:
        findings.append("non_agent_pr_modified")
    if computed["add_human_review_required"] != (
        computed["detected"] and computed["sensitive_change"]
    ):
        findings.append("human_review_routing_condition_invalid")
    if computed["comment_action"] == "create" and case.get("prior_sticky_comment_count", 0):
        findings.append("duplicate_sticky_comment_would_be_created")

    return {
        "case_id": case_id,
        "case_type": case_type,
        "case_valid": not findings,
        **computed,
        "findings": findings,
    }


def evaluate_ai_authored_pr_provenance_fixture(
    fixture_set: Any, workflow_text: Any
) -> dict[str, Any]:
    """Evaluate the fixture contract and trusted workflow text deterministically."""

    fixture = _as_dict(fixture_set)
    findings = _validate_fixture_contract(fixture)
    workflow_findings = evaluate_workflow_text(workflow_text)
    findings.extend(workflow_findings)

    cases = [_as_dict(item) for item in _as_list(fixture.get("fixture_cases"))]
    case_types = {str(case.get("case_type") or "") for case in cases}
    missing_cases = sorted(REQUIRED_CASE_TYPES - case_types)
    if missing_cases:
        findings.extend(f"required_case_missing:{case_type}" for case_type in missing_cases)
    duplicate_case_ids = {
        case_id
        for case_id in {str(case.get("case_id") or "") for case in cases}
        if case_id and sum(str(case.get("case_id") or "") == case_id for case in cases) > 1
    }
    findings.extend(f"duplicate_case_id:{case_id}" for case_id in sorted(duplicate_case_ids))

    case_results = [_evaluate_case(case) for case in cases]
    for case_result in case_results:
        if not case_result["case_valid"]:
            findings.extend(
                f"{case_result['case_id']}:{finding}"
                for finding in case_result.get("findings", [])
            )

    simulated_output = str(fixture.get("simulated_evaluator_output") or "").strip()
    if simulated_output in FORBIDDEN_EVALUATOR_OUTPUTS:
        findings.append(f"forbidden_output_claim_detected:{simulated_output}")

    findings = _dedupe(findings)
    valid = not findings
    positive_cases = [result for result in case_results if "detected" in result]
    return {
        "ai_pr_provenance_valid": valid,
        "ai_pr_provenance_invalid": not valid,
        "ai_pr_provenance_findings": findings,
        "workflow_security_valid": not workflow_findings,
        "workflow_security_findings": workflow_findings,
        "agent_pr_detected": any(result.get("detected") for result in positive_cases),
        "non_agent_pr_detected": any(
            result.get("detected") is False for result in positive_cases
        ),
        "provenance_label_required": any(
            result.get("add_pr_by_ai") for result in positive_cases
        ),
        "provenance_comment_required": any(
            result.get("comment_action") in {"create", "update"}
            for result in positive_cases
        ),
        "sensitive_change_detected": any(
            result.get("sensitive_change") for result in positive_cases
        ),
        "human_review_required": any(
            result.get("add_human_review_required") for result in positive_cases
        ),
        "reviewer_routing_required": any(
            result.get("review_routing_required") for result in positive_cases
        ),
        "ready_for_review": valid,
        "case_results": case_results,
    }


__all__ = [
    "FORBIDDEN_EVALUATOR_OUTPUTS",
    "REQUIRED_WORKFLOW_OUTPUTS",
    "detect_agent_pr",
    "evaluate_ai_authored_pr_provenance_fixture",
    "evaluate_workflow_text",
]
